config/routes.rb
Rails.application.routes.draw do
  get 'maps/terms'
  get 'maps/contact'
  get 'maps/about'
  resources :maps
  root to: 'maps#index'
  get 'maps/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  after_validation :geocode
  has_many_attached :images
  # ここで暗黙の関連付けを複数形にしていることに注意
  scope :with_eager_loaded_images, -> { eager_load(images_attachments: :blob) }

  private
  def geocode
    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=#{ENV['GOOGLE_MAPS_API_KEY']}")
    res = HTTP.get(uri).to_s
    response = JSON.parse(res)
    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
  end

  # defaltで表示させる内容。
  def self.favorite
    Map.where.not(favorite_flag: nil).order(:favorite_flag)
  end

  # 検索フォームにより絞り込まれた店のデータを出力する。
  def self.search(search, category) # Controllerから渡されたパラメータによって、station_nameとcategoryカラムを部分一致で絞り込む
    if search
      key = ""
      val = ["%#{category}%", "%#{search[0]}%"]
      (search.size - 1).times do |i|
        key += " or station_name LIKE ?"
        val = val.push("%#{search[i+1]}%")
      end
      val = val.unshift("category LIKE ? and (station_name LIKE ?#{key})")
     Map.where(val)
    else
      Map.where("category LIKE ?", "%#{category}%")
    end
  end

  # 検索フォームにより絞り込まれた駅のデータを出力する。
  def self.station_num(search, category) # Controllerから渡されたパラメータによって、検索された駅の数を調べる。
    if search
      key = ""
      val = ["%駅%", "%#{category}%", "%#{search[0]}%"]
      (search.size - 1).times do |i|
        key += " or station_name LIKE ?"
        val = val.push("%#{search[i+1]}%")
      end
      val = val.unshift("station_name NOT LIKE ? and category LIKE ? and (station_name LIKE ?#{key})")
      # 駅名とカテゴリで絞り込み、ハッシュで返す。# group byによって、検索された駅の数を調べる。
      Map.select("station_name").where(val).group(:station_name).size
    else
      Map.select("station_name").where("category LIKE ? and station_name NOT LIKE ?", "%#{category}%", "%駅%").group(:station_name).size
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.search(params[:search],params[:category])
    @maps_station_num = Map.station_num(params[:search],params[:category])
    @maps_favorite = Map.favorite
    request.user_agent       #=> "Mozilla/5.0 (Linux; Android 4.3; Nexus 7 ..."
    request.device_type      #=> :smartphone
    request.os               #=> "Android"
    request.os_version       #=> "4.3"
    request.browser          #=> "Chrome"
    request.browser_version  #=> "29.0.1547.72"
    request.from_pc?         #=> false
    request.from_smartphone? #=> true
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:station_name, :category, :phone_number, :store_name, :address, :latitude, :longitude, :business_hours, :HP, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>靴サーチ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-multiselect-widget/3.0.0/jquery.multiselect.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= javascript_include_tag "map.js" %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <% if request.from_pc? then %>
    <%= stylesheet_link_tag    'pc/index', 'pc/index_favorite', 'pc/maps', 'pc/show', 'pc/about', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
    <%= stylesheet_link_tag    'mobile/index', 'mobile/index_favorite', 'mobile/maps', 'mobile/show', 'mobile/about',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <% end %>
  </head>

  <body>
    <!-- サイドオープン時メインコンテンツを覆う-->
    <div class="overlay" id="js__overlay"></div>

    <nav class="side-menu">
      <h4 class='search_box_item'><a class='link_search' href="/">ホームへ</a></h4>
      <h4 class='search_box_title'>エリア</h4>
      <ul class='search_tree'>
        <li class='link'><%= link_to '吉祥寺', {controller: "maps", action: "index", search: "吉祥寺"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to '下北沢', {controller: "maps", action: "index", search: "下北沢"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to '渋谷', {controller: "maps", action: "index", search: "渋谷"}, {:class => 'link_search'}  %></li>
      </ul>
      <h4 class='search_box_title'>カテゴリ</h4>
      <ul class='search_tree'>
        <li class='link'><%= link_to 'メンズ', {controller: "maps", action: "index", category: "メンズ"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'レディース', {controller: "maps", action: "index", category: "レディース"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'ユニセックス', {controller: "maps", action: "index", category: "ユニセックス"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'スニーカー', {controller: "maps", action: "index", category: "スニーカー"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'サンダル', {controller: "maps", action: "index", category: "サンダル"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'シューケア', {controller: "maps", action: "index", category: "シューケア"}, {:class => 'link_search'}  %></li>
        <li class='link'><%= link_to 'メンズ小さいサイズ', {controller: "maps", action: "index", category: "メンズ小さいサイズ"}, {:class => 'link_search'}  %></li>
      </ul>
    </nav>


    <input type="checkbox" class="check" id="checked">
    <label class="menu-btn" for="checked">
      <span class="bar top"></span>
      <span class="bar middle"></span>
      <span class="bar bottom"></span>
    </label>
    <label class="close-menu" for="checked"></label>




    <!-- メインコンテンツ -->
    <div class="wrapper">
      <!-- ナビバーを表示 -->
      <header>
        <div id='navbar'>
          <!-- 画像の挿入 -->
          <%= link_to image_tag('logo.png', id: 'logo'), maps_path, class: 'maps_path' %>
          <div id='sub_title'>
            靴サーチとは、自分の欲しい靴が都内のどこで売られているかを簡単に見つけられるサービスです。<span class='br'/>
            掲載している靴屋は全て靴好きの運営者オススメの靴屋であり、一つ一つのお店にコメントをつけているのでわかりやすくなっています。</div>
          <hr>
        </div>
      </header>
      <%= yield %>
      <footer>
        <div id="footer_layout">
          <div id="footer_logo">
            <%= link_to image_tag('logo.png', id: 'footer_logo_img'), maps_path, id: 'footer_maps_path' %>
            <div id='footer_sub_title'>
                靴サーチでは、そのお店で扱っている靴のサイズを表記していくことで「気に入ったけどサイズがなくて買えなかった」というような悩みにも応えていきます。<sup>注１</sup>
            </div>
          </div>
          <ul class="footer_cell">
            <h4 class='footer_search_title'>エリア</h4>
            <li class="footer_item"><%= link_to '吉祥寺', {controller: "maps", action: "index", search: "吉祥寺"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to '下北沢', {controller: "maps", action: "index", search: "下北沢"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to '渋谷', {controller: "maps", action: "index", search: "渋谷"}, {:class => 'footer_link'}  %></li>
          </ul>
          <ul class="footer_cell">
            <h4 class='footer_search_title'>カテゴリ</h4>
            <li class="footer_item"><%= link_to 'スニーカー', {controller: "maps", action: "index", category: "スニーカー"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'スポーツ', {controller: "maps", action: "index", category: "スポーツ"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'ビジネスシューズ', {controller: "maps", action: "index", category: "ビジネスシューズ"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'ブーツ', {controller: "maps", action: "index", category: "ブーツ"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'ユニセックス', {controller: "maps", action: "index", category: "ユニセックス"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'キッズ', {controller: "maps", action: "index", category: "キッズ"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'サンダル', {controller: "maps", action: "index", category: "サンダル"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'シューケア', {controller: "maps", action: "index", category: "シューケア"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'メンズ専門', {controller: "maps", action: "index", category: "メンズ専門"}, {:class => 'footer_link'}  %></li>
            <li class="footer_item"><%= link_to 'レディス専門', {controller: "maps", action: "index", category: "レディス専門"}, {:class => 'footer_link'}  %></li>
          </ul>
          <ul class="footer_cell">
            <h4 class='footer_search_title'>靴サーチについて</h4>
            <li class="footer_item"><a href="/maps/about">靴サーチとは</a></li>
            <li class="footer_item"><a href="/maps/contact">お問い合わせ</a></li>
            <li class="footer_item"><a href="/maps/terms">利用規約</a></li>
          </ul>
          <div class='annotation'><sup>*1</sup>靴のサイズは当サイト運営者が調査するもので店舗オーナー様による表記ではないので、誤りがある場合があります。</div>
          <small id="copyright">©&nbsp;2018&nbsp;kubota-ryotaro</small>
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/maps/about.html.erb
<%= render 'shared/search_list' %>
<div id="about">
  <div id='search_nav'>
    <nav id='pankuzu_nav'>
      <ol id='pankuzu_ol'>
        <li class='pankuzu_li'><%= link_to 'HOME', maps_path %></li>
        <li class='pankuzu_li'>靴サーチとは</li>
      </ol>
    </nav>
  </div>
  <div id="about_content">
    <h1>靴サーチとは</h1>
    <p>靴サーチとは、自分の欲しい靴が都内のどこで売られているかを簡単に見つけられるサービスです。</p>
    <p>靴屋をエリアや靴の種類で検索できるだけでなく、掲載している靴屋は全て靴好きの運営者オススメの靴屋であり、一つ一つのお店にコメントをつけているのでわかりやすくなっております。</p>
    <p>また、そのお店で扱っている靴のサイズも表記していくことで「気に入ったけどサイズがなくて買えなかった」というような悩みにも応えていきます。<sup>注１</sup></p>
    <p>「自分好みの靴屋さんをリサーチしたい」「自分の足サイズに合う靴屋さんの情報が欲しい」などなど、実は靴を買う人達って、人によって様々な都合を抱えているんですよね。</p>
    <p>例えば、</p>
    <p>「僕は男性だけど足サイズが24㎝でメンズ物の靴が買えなくて困っている」という人や「私は女性ですが25㎝もあってレディス物がたまに買えない」というサイズにストレスを感じている人達や、</p>
    <p>「買いたい靴の種類は決まっているので、その種類を扱っている靴屋で検索したい」という人や、「事前に商品や店内の写真を見て、品揃えや雰囲気を確認しておきたい」という人もいます。</p>
    <p>このような場面に出くわす方々に少しでも有益な情報を提供できたらなと思い、このサービスを運営しています。</p>
  </div>
</div>

app/views/maps/contact.html.erb
<%= render 'shared/search_list' %>
<div id="about">
  <div id='search_nav'>
    <nav id='pankuzu_nav'>
      <ol id='pankuzu_ol'>
        <li class='pankuzu_li'><%= link_to 'HOME', maps_path %></li>
        <li class='pankuzu_li'>お問い合わせ</li>
      </ol>
    </nav>
  </div>
  <div id="about_content">
    <h1>お問い合わせ</h1>
    <p>こちら現在作成中です。ご不便をおかけいたします。</p>
    <p>rk0822pu4@gmail.com こちら管理人のメールアドレスです。</p>
  </div>
</div>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<!-- コンテンツ作成 -->
<div id='body_background'>
  <div class='br br_box'></div>
  <!-- TOPページを表示 -->
  <% unless params[:search].present? or params[:category].present? %>
    <div id='content'>
      <%= render 'shared/search_list' %>
      <div id='fav_search_content'>
        <div class='search_result_station'>おすすめトップ１０</div>
        <% @maps_favorite.each do |map| %>
          <div class='fav_content'>
            <%= link_to map, class: 'fav_store_detail' do %>
            <div class='fav_tatile_name'>
              <%= map.favorite_flag %>. <%= map.store_name %>
            </div>
            <div class='fav_store_image'><!-- 画像の挿入 -->
              <%= image_tag("#{map.station_name}/#{map.store_name}/sub_1", :class => 'fav_image', :size => "270x180") %>
            </div>
            <!-- 詳細ボタン -->
            <%= link_to map, :class => 'detail_btn distribute_btn' do %>
              <div class='detail_btn_text'>詳細を見る</div>
            <% end %>
              <table class='fav_content_table'>
                <tbody>
                  <tr>
                    <th class='fav_item_head'>エリア</th>
                    <td class='item_data'>
                      <%= link_to({controller: "maps", action: "index", search: "#{map.station_name}"}) do  %>
                        <div class='square_area'><%= map.station_name %></div>
                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <th class='fav_item_head'>テキスト</th>
                    <td class='item_data'><%= simple_format(map.text[0, 130] + '...', :id => 'detail_text') %></td>
                  </tr>
                  <tr>
                    <th class='fav_item_head'>カテゴリ</th>
                    <td class='item_data'>
                      <% map.category[1, map.category.length].split("#").each do |category| %>
                        <%= link_to({controller: "maps", action: "index", category: "#{category}"}) do  %>
                          <div class='square_category'><%= category %></div>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>

    <!-- 絞り込み後 -->
    <div id='content'>
      <%= render 'shared/search_list' %>
      <div id='search_content'>
        <!-- パンくずリスト -->
        <% if params[:search].present? or params[:category].present? %>
          <div id='search_nav'>
            <nav id='pankuzu_nav'>
              <ol id='pankuzu_ol'>
                <li class='pankuzu_li'><%= link_to 'HOME', maps_path %></li>
                <% if params[:search].present? %>
                  <li class='pankuzu_li'><%= params[:search] %></li>
                <% else %>
                  <li class='pankuzu_li'><%= params[:category] %></li>
                <% end %>
              </ol>
            </nav>
            <div id='search_result'>
              <span>全<%= @maps_station_num.values.inject(:+) %>件</span>
            </div>
          </div>
        <% end %>
        <% @maps_station_num.each do |station, num| %><!-- 駅の数だけdivを作る。 -->
          <ul class="contents">
            <!-- 駅名とカテゴリと検索結果数を表示 -->
            <input type="checkbox" id="label_<%= station %>"/>
            <label for="label_<%= station %>" class='search_result_station'>
              <div class="label_text"><%= station %>駅周辺<span class='space'></span><span><%= params[:category] if params[:category].present? %></span><span class='space'></span>検索結果 <%= num %>件</div>
              <!-- カテゴリ絞り込み時のみ、アコーディオンボタンを設置する。-->
              <% if params[:category].present? %>
                <div class='grad_btn'><span class="triangle"></span></div>
              <% end %>
            </label>

            <!-- エリアで絞り込んだ時と、カテゴリで絞り込んだ時のcssを分ける。 -->
            <div class="search_store<%= "_category" if params[:category].present? %>">
              <% @maps.each do |map| %>
                <% if map.store_name.present? and map.station_name === station %><!-- 駅名ごとに振り分ける。 -->
                  <li class='content'>
                    <!-- 画像の挿入 -->
                    <% if File.exist?("#{Rails.root}/app/assets/images/#{map.station_name}/#{map.store_name}/sub_1.jpg") %>
                      <div class="index_img_div">
                        <%= link_to map do %>
                          <span><%= image_tag "#{map.station_name}/#{map.store_name}/sub_1", :size => "170x120" , :class => 'index_img' %></span>
                        <% end %>
                      </div>
                    <% end %>
                    <!-- 詳細ボタン -->
                    <%= link_to map, :class => 'detail_btn' do %>
                      <div class='detail_btn_text'>詳細を見る</div>
                    <% end %>
                    <div class='store_info'>
                      <%= link_to map, :class => 'store_info_link' do %>
                        <div class='store_info_msg store_info_name'><%= map.store_name %></div>
                        <%= simple_format(map.text[0, 70] + '...', {class: 'store_info_text'}, wrapper_tag: 'div') %>
                      <% end %>
                      <div class='store_info_btn'><!-- categoryをボタンで表示する。 -->
                        <% map.category[1, map.category.length].split("#").each do |category| %>
                          <%= link_to({controller: "maps", action: "index", category: "#{category}"}) do  %>
                            <div class='store_info_category'><%= category %></div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </div>
          </ul>
        <% end %>
        <!-- 地図を表示 -->
        <div id='map_idx'></div>
      </div>
    </div>
  <% end %>
  <div class='page_top'><a href="#header">ページの一番上に戻る</a></div>
</div>

<!-- GoogleMapsAPIのセッティング -->
<script type="text/javascript">
  function initMap() {
    // 入力した駅を中心とする地図のセッティング
    <% if params[:search].present? %>// 駅で絞り込みをかけたら、その駅を中心とする。
      <% @maps.each do |map| %>
        if(typeof(flag) != 'undefined') { //駅データ取得のチェック
        } else {
        if( <%= map.station_name.try(:include?, "駅") %> ) {
          var latlng = {lat: <%= map.latitude %>, lng: <%= map.longitude %>};
          var map = new google.maps.Map(document.getElementById('map_idx'), {
            zoom: 15,
            center: latlng
          });
          var transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);
          // 駅データを取得したらフラグを立てる。
          var flag = 'ok';
        }
        }
      <% end %>
    <% else %>  //カテゴリで絞り込みをかけたら、一律で渋谷駅を中心とする。
      var latlng = {lat: 35.658, lng: 139.702};
      var map = new google.maps.Map(document.getElementById('map_idx'), {
        zoom: 11,
        center: latlng
      });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);
    <% end %>



      // 入力した駅にヒットしたそれぞれの店を出力していく。
      <% @maps.each do |map| %>
        (function(){
          if( <%= map.station_name.try(:exclude?, "駅") %>) {
            var address = "住所：<%= map.address %>";
            var store_name = "<%= map.store_name %>";
            var infowindow = new google.maps.InfoWindow({ content: "店名: <%= map.store_name %><br><%= map.address %>" });

            // マーカーの設定
            var marker = new google.maps.Marker({
              position:{lat: <%= map.latitude %>, lng: <%= map.longitude %>},
              map: map,
              title: store_name,
              icon: null,
              animation: null
            });

            // クリックしたら吹き出しを出力し、店名と住所を表示する。
            marker.addListener('click', function() { infowindow.open(map, marker); });
          }
        })();
  <% end %>
  }
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap">
</script>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/terms.html.erb
<%= render 'shared/search_list' %>
<div id="about">
  <div id='search_nav'>
    <nav id='pankuzu_nav'>
      <ol id='pankuzu_ol'>
        <li class='pankuzu_li'><%= link_to 'HOME', maps_path %></li>
        <li class='pankuzu_li'>利用規約</li>
      </ol>
    </nav>
  </div>
  <div id="about_content">
    <h1>利用規約</h1>
    <p>この利用規約（以下，「本規約」といいます。）は，靴サーチ（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。ユーザーの皆さまには，本規約に従って，本サービスをご利用いただきます。</p>
    <h2>第1条（適用）</h2>
    <p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>

    <h2>第2条（禁止事項）</h2>
    <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
    <ol>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>当社のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
      <li>当社のサービスの運営を妨害するおそれのある行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>その他，当社が不適切と判断する行為</li>
    </ol>
    <h2>第3条（本サービスの提供の停止等）</h2>
    <ol>
      <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
      <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他，当社が本サービスの提供が困難と判断した場合</li>
      </ol>
      <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</li>
    </ol>
    <h2>第4条（利用制限および登録抹消）</h2>
    <ol>
      <li>当社は，以下の場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</li>
      <ol>
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
      </ol>
      <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
    </ol>
    <h2>第5条（免責事項）</h2>
    <ol>
      <li>当社の債務不履行責任は，当社の故意または重過失によらない場合には免責されるものとします。</li>
      <li>当社は，何らかの理由によって責任を負う場合にも，通常生じうる損害の範囲内かつ有料サービスにおいては代金額（継続的サービスの場合には1か月分相当額）の範囲内においてのみ賠償の責任を負うものとします。</li>
      <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
    </ol>
    <h2>第6条（サービス内容の変更等）</h2>
    <p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
    <h2>第7条（利用規約の変更）</h2>
    <p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</p>
    <h2>第8条（通知または連絡）</h2>
    <p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。</p>
    <h2>第9条（権利義務の譲渡の禁止）</h2>
    <p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
    <h2>第10条（準拠法・裁判管轄）</h2>
    <ol>
      <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
      <li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
    </ol>
    <p>以上</p>

  </div>
</div>